d: 10
max_distance: 9
device: null
action_spec: null
obs_shape: null
obs_prepro: null
env_factory: null
env_name: null
env_family: null
model_cfg: null
optimizer_cfg: null
n_samples: 400000
batch_size: 32
discount: 0.9
reg_neg: 0.0
replay_buffer_size: 400000
log_dir: '/tmp/rl_laprepr/log'
total_train_steps: 400000
print_freq: 1000
save_freq: 10000
max_episode_steps: 200
seed: 1234
env_name: GridRoom-4
env_family: Grid-v0
nn_library: haiku-v2
lr: 0.0001
use_wandb: True
algorithm: coef-a
regularization_weight: 5.0
