d: 10
max_distance: 9
device: null
action_spec: null
obs_shape: null
obs_prepro: null
env_factory: null
env_name: null
env_family: null
model_cfg: null
optimizer_cfg: null
n_samples: 100000
batch_size: 32
discount: 0.9
w_neg: 5.0
c_neg: 1.0
reg_neg: 0.0
replay_buffer_size: 100000
log_dir: '/tmp/rl_laprepr/log'
total_train_steps: 200000
print_freq: 1000
save_freq: 10000
max_episode_steps: 50
seed: 1337
env_name: GridRoom-1
env_family: Grid-v0
