d: 11
max_distance: 9
device: null
action_spec: null
obs_shape: null
obs_prepro: null
env_factory: null
env_name: null
env_family: null
model_cfg: null
optimizer_cfg: null
n_samples: 1000000
batch_size: 32
discount: 0.9
reg_neg: 0.0
replay_buffer_size: 1000000
log_dir: '/tmp/rl_laprepr/log'
total_train_steps: 4000000
print_freq: 1000
save_freq: 10000
max_episode_steps: 50
seed: 1234
env_name: GridRoomSym-4
env_family: Grid-v0
nn_library: haiku-v2
lr: 0.0001
use_wandb: True
hidden_dims:
  - 256
  - 256
update_dual_every: 1
reset_dual_every: 4000000
update_dual_after: 0
update_barrier_every: 1
activation: relu
use_cosine_similarity_v2: True
eigval_precision_order: 16
direct_rotation: True
save_eig: True
algorithm: dual-exact
dual_initial_val: 0.0
detach_symmetric_constraints: True
orthogonality_tolerance: 0.0
optimize_dual_logs: False
use_lower_triangular: False   # Add the option to use lower triangular matrix
error_estimate_update_rate: 0.1
lr_duals: 0.01
min_duals: -100
max_duals: 100
normalize_dual_updates: False
implicit_orthogonality_weight: 1.0
use_error_mean: False
constant_reset: False
reset_proportion: 0.5
dual_threshold: 1.0
barrier_threshold: 0.001
barrier_increase_factor: 1.1
barrier_initial_val: 0.0
lr_barrier_coefs: 0.001
min_barrier_coefs: -100
max_barrier_coefs: 100
use_barrier_update_v2: True
use_additive_duals: False
