d: 10
max_distance: 9
device: null
action_spec: null
obs_shape: null
obs_prepro: null
env_factory: null
env_name: null
env_family: null
model_cfg: null
optimizer_cfg: null
n_samples: 1000000
batch_size: 32
discount: 0.9
reg_neg: 0.0
replay_buffer_size: 1000000
log_dir: '/tmp/rl_laprepr/log'
total_train_steps: 400000
print_freq: 1000
save_freq: 10000
max_episode_steps: 50
seed: 1234
env_name: GridRoom-1
env_family: Grid-v0
nn_library: haiku-v2
lr: 0.0001
use_wandb: True
hidden_dims:
  - 256
  - 256
update_dual_every: 1
activation: relu
algorithm: dual
dual_initial_val: 1.0
detach_symmetric_constraints: True
orthogonality_tolerance: 0.001
optimize_dual_logs: True
use_lower_triangular: False   # Add the option to use lower triangular matrix
error_estimate_update_rate: 0.1
lr_duals: 0.0001
min_duals: 0
max_duals: 1000000
normalize_dual_updates: False
implicit_orthogonality_weight: 1.0
use_error_mean: False
update_dual_after: 0