input_dim: 2
d: 11
n_samples: 200000
batch_size: 2048
discount: 0.9
log_dir: './logs'
total_train_steps: 20000
print_freq: 200
max_episode_steps: 50
seed: 1234
env_name: GridRoomSmall-1
env_family: Grid-v0
lr: 0.00005
use_wandb: True
hidden_dims: 128
activation: relu
eigval_precision_order: 16
direct_rotation: True
save_eig: False
save_model: False
save_model_every: 50000
do_plot_eigenvectors: True
obs_mode: xy
window_size: 180
reduction_factor: 1
algorithm: algnn
error_update_rate: 1
q_error_update_rate: 0.1
normalize_graph_loss: False
barrier_initial_val: 2.0
lr_barrier_coefs: 1.0
min_barrier_coefs: 0
max_barrier_coefs: 10000
use_barrier_normalization: False
use_barrier_for_duals: False
lr_duals: 0.0001
lr_dual_velocities: 0.1
min_duals: -100
max_duals: 100
permute_step: 20000
deactivate_training: False
device: cpu