d: 11
n_samples: 100000
batch_size: 1024
discount: 0.9
log_dir: '/tmp/rl_laprepr/log'
total_train_steps: 10000000
print_freq: 1000
save_freq: 10000
max_episode_steps: 50
seed: 1234
env_name: GridRoom-16
env_family: Grid-v0
lr: 0.001
use_wandb: True
hidden_dims:
  - 256
  - 256
  - 256
activation: relu
eigval_precision_order: 16
direct_rotation: True
save_eig: True
save_model: False
save_model_every: 100000
algorithm: al-gdo
use_abs_square_estimation: False
update_dual_every: 1
reset_dual_every: 1000000000000
update_dual_after: 0
update_barrier_every: 1
dual_initial_val: 0.0
detach_symmetric_constraints: True
orthogonality_tolerance: 0.0
optimize_dual_logs: False
use_lower_triangular: False   # Add the option to use lower triangular matrix
error_estimate_update_rate: 1
sq_error_estimate_update_rate: 0.1
lr_duals: 0.0001
lr_dual_velocities: 0.1
min_duals: -100
max_duals: 100
normalize_dual_updates: False
implicit_orthogonality_weight: 1.0
use_error_mean: False
constant_reset: False
reset_proportion: 0.5
dual_threshold: 1.0
barrier_threshold: 0.001
barrier_increase_factor: 1.1
barrier_initial_val: 1.0
lr_barrier_coefs: 1.0
min_barrier_coefs: 0
max_barrier_coefs: 10000
barrier_update_version: 2
use_additive_duals: False
use_barrier_normalization: False
barrier_beta: 0.001
use_barrier_for_duals: False
barrier_mean_or_sum: sum
